// GENERATED by tool/solve_levels.dart. Do not edit by hand.
// Each entry is an engine-verified winning player placement.
import '../engine/game_object.dart';

final Map<int, List<GameObject>> kLevelSolutions = {
  1: [],
  2: [
    GameObject(type: ObjectType.peg, x: 100.0, y: 260.0),
    GameObject(type: ObjectType.peg, x: 220.0, y: 380.0),
  ],
  3: [
    GameObject(type: ObjectType.peg, x: 260.0, y: 300.0),
    GameObject(type: ObjectType.peg, x: 220.0, y: 300.0),
  ],
  4: [
    GameObject(type: ObjectType.peg, x: 100.0, y: 100.0),
    GameObject(type: ObjectType.peg, x: 220.0, y: 220.0),
    GameObject(type: ObjectType.peg, x: 180.0, y: 500.0),
  ],
  5: [
    GameObject(type: ObjectType.peg, x: 260.0, y: 220.0),
    GameObject(type: ObjectType.peg, x: 100.0, y: 380.0),
    GameObject(type: ObjectType.peg, x: 260.0, y: 340.0),
  ],
  6: [GameObject(type: ObjectType.booster, x: 180.0, y: 180.0, angle: 135.0)],
  7: [GameObject(type: ObjectType.booster, x: 60.0, y: 140.0, angle: 90.0)],
  8: [
    GameObject(type: ObjectType.booster, x: 180.0, y: 180.0, angle: 90.0),
    GameObject(type: ObjectType.peg, x: 180.0, y: 500.0),
  ],
  9: [GameObject(type: ObjectType.booster, x: 60.0, y: 140.0, angle: 90.0)],
  10: [
    GameObject(type: ObjectType.booster, x: 300.0, y: 140.0, angle: 270.0),
    GameObject(type: ObjectType.peg, x: 100.0, y: 420.0),
    GameObject(type: ObjectType.peg, x: 260.0, y: 540.0),
  ],
  11: [
    GameObject(type: ObjectType.spring, x: 180.0, y: 380.0, angle: 45.0),
    GameObject(type: ObjectType.spring, x: 260.0, y: 260.0, angle: 270.0),
    GameObject(type: ObjectType.peg, x: 140.0, y: 620.0),
  ],
  12: [
    GameObject(type: ObjectType.spring, x: 60.0, y: 180.0, angle: 90.0),
    GameObject(type: ObjectType.spring, x: 20.0, y: 540.0, angle: 45.0),
    GameObject(type: ObjectType.peg, x: 340.0, y: 260.0),
  ],
  13: [
    GameObject(type: ObjectType.spring, x: 100.0, y: 540.0, angle: 45.0),
    GameObject(type: ObjectType.spring, x: 300.0, y: 420.0),
    GameObject(type: ObjectType.booster, x: 260.0, y: 220.0, angle: 45.0),
  ],
  14: [GameObject(type: ObjectType.spring, x: 180.0, y: 420.0, angle: 90.0)],
  15: [
    GameObject(type: ObjectType.spring, x: 300.0, y: 340.0, angle: 45.0),
    GameObject(type: ObjectType.spring, x: 100.0, y: 580.0, angle: 45.0),
    GameObject(type: ObjectType.peg, x: 300.0, y: 460.0),
  ],
  16: [
    GameObject(type: ObjectType.magnet, x: 100.0, y: 20.0),
    GameObject(type: ObjectType.magnet, x: 180.0, y: 220.0),
  ],
  17: [
    GameObject(type: ObjectType.magnet, x: 220.0, y: 140.0),
    GameObject(type: ObjectType.peg, x: 340.0, y: 500.0),
  ],
  18: [
    GameObject(type: ObjectType.magnet, x: 260.0, y: 20.0),
    GameObject(type: ObjectType.booster, x: 140.0, y: 380.0, angle: 90.0),
    GameObject(type: ObjectType.peg, x: 220.0, y: 580.0),
  ],
  19: [
    GameObject(type: ObjectType.spring, x: 60.0, y: 340.0, angle: 45.0),
    GameObject(type: ObjectType.peg, x: 340.0, y: 460.0),
    GameObject(type: ObjectType.magnet, x: 220.0, y: 260.0),
    GameObject(type: ObjectType.peg, x: 60.0, y: 620.0),
    GameObject(type: ObjectType.peg, x: 180.0, y: 620.0),
  ],
  20: [
    GameObject(type: ObjectType.magnet, x: 100.0, y: 140.0),
    GameObject(type: ObjectType.magnet, x: 180.0, y: 220.0),
  ],
  21: [
    GameObject(type: ObjectType.prism, x: 180.0, y: 300.0, angle: 45.0),
    GameObject(type: ObjectType.peg, x: 220.0, y: 580.0),
  ],
  22: [
    GameObject(type: ObjectType.booster, x: 60.0, y: 100.0, angle: 225.0),
    GameObject(type: ObjectType.peg, x: 60.0, y: 420.0),
  ],
  23: [GameObject(type: ObjectType.spring, x: 300.0, y: 500.0, angle: 315.0)],
  24: [
    GameObject(type: ObjectType.prism, x: 180.0, y: 100.0, angle: 225.0),
    GameObject(type: ObjectType.prism, x: 20.0, y: 340.0, angle: 45.0),
    GameObject(type: ObjectType.magnet, x: 300.0, y: 420.0),
    GameObject(type: ObjectType.peg, x: 260.0, y: 500.0),
    GameObject(type: ObjectType.peg, x: 60.0, y: 500.0),
  ],
  25: [
    GameObject(type: ObjectType.spring, x: 60.0, y: 100.0, angle: 315.0),
    GameObject(type: ObjectType.prism, x: 140.0, y: 580.0, angle: 45.0),
    GameObject(type: ObjectType.booster, x: 340.0, y: 420.0, angle: 45.0),
  ],
  26: [],
  27: [
    GameObject(type: ObjectType.booster, x: 180.0, y: 100.0, angle: 135.0),
    GameObject(type: ObjectType.teleporter, x: 20.0, y: 20.0, link: 101),
    GameObject(type: ObjectType.teleporter, x: 340.0, y: 500.0, link: 101),
    GameObject(type: ObjectType.peg, x: 100.0, y: 300.0),
  ],
  28: [
    GameObject(type: ObjectType.teleporter, x: 180.0, y: 260.0, link: 100),
    GameObject(type: ObjectType.teleporter, x: 300.0, y: 420.0, link: 100),
    GameObject(type: ObjectType.peg, x: 180.0, y: 540.0),
  ],
  29: [
    GameObject(type: ObjectType.peg, x: 100.0, y: 580.0),
    GameObject(type: ObjectType.booster, x: 60.0, y: 340.0, angle: 135.0),
    GameObject(type: ObjectType.teleporter, x: 20.0, y: 340.0, link: 102),
    GameObject(type: ObjectType.teleporter, x: 180.0, y: 580.0, link: 102),
  ],
  30: [
    GameObject(type: ObjectType.booster, x: 180.0, y: 180.0, angle: 315.0),
    GameObject(type: ObjectType.teleporter, x: 100.0, y: 580.0, link: 101),
    GameObject(type: ObjectType.teleporter, x: 260.0, y: 100.0, link: 101),
    GameObject(type: ObjectType.peg, x: 60.0, y: 340.0),
  ],
  31: [
    GameObject(type: ObjectType.spring, x: 60.0, y: 220.0, angle: 90.0),
    GameObject(type: ObjectType.booster, x: 100.0, y: 180.0, angle: 90.0),
    GameObject(type: ObjectType.peg, x: 100.0, y: 540.0),
  ],
  32: [
    GameObject(type: ObjectType.spring, x: 180.0, y: 140.0, angle: 90.0),
    GameObject(type: ObjectType.prism, x: 260.0, y: 580.0, angle: 315.0),
    GameObject(type: ObjectType.booster, x: 100.0, y: 460.0, angle: 45.0),
  ],
  33: [
    GameObject(type: ObjectType.spring, x: 300.0, y: 500.0, angle: 315.0),
    GameObject(type: ObjectType.prism, x: 140.0, y: 380.0, angle: 315.0),
    GameObject(type: ObjectType.magnet, x: 260.0, y: 20.0),
    GameObject(type: ObjectType.peg, x: 100.0, y: 620.0),
  ],
  34: [
    GameObject(type: ObjectType.spring, x: 60.0, y: 260.0, angle: 90.0),
    GameObject(type: ObjectType.booster, x: 140.0, y: 260.0, angle: 90.0),
    GameObject(type: ObjectType.prism, x: 100.0, y: 460.0, angle: 90.0),
  ],
  35: [
    GameObject(type: ObjectType.magnet, x: 220.0, y: 20.0),
    GameObject(type: ObjectType.spring, x: 300.0, y: 380.0, angle: 315.0),
    GameObject(type: ObjectType.booster, x: 140.0, y: 260.0, angle: 270.0),
    GameObject(type: ObjectType.peg, x: 300.0, y: 620.0),
    GameObject(type: ObjectType.peg, x: 60.0, y: 580.0),
  ],
  36: [
    GameObject(type: ObjectType.booster, x: 60.0, y: 300.0, angle: 45.0),
    GameObject(type: ObjectType.spring, x: 60.0, y: 340.0),
    GameObject(type: ObjectType.booster, x: 140.0, y: 60.0, angle: 270.0),
  ],
  37: [
    GameObject(type: ObjectType.magnet, x: 260.0, y: 140.0),
    GameObject(type: ObjectType.prism, x: 220.0, y: 620.0, angle: 315.0),
    GameObject(type: ObjectType.spring, x: 60.0, y: 460.0),
    GameObject(type: ObjectType.prism, x: 60.0, y: 260.0, angle: 45.0),
  ],
  38: [
    GameObject(type: ObjectType.teleporter, x: 180.0, y: 260.0, link: 100),
    GameObject(type: ObjectType.teleporter, x: 300.0, y: 180.0, link: 100),
    GameObject(type: ObjectType.spring, x: 60.0, y: 580.0, angle: 315.0),
  ],
  39: [
    GameObject(type: ObjectType.spring, x: 60.0, y: 220.0, angle: 90.0),
    GameObject(type: ObjectType.prism, x: 260.0, y: 500.0, angle: 315.0),
    GameObject(type: ObjectType.booster, x: 60.0, y: 500.0, angle: 90.0),
    GameObject(type: ObjectType.magnet, x: 100.0, y: 500.0),
  ],
  40: [
    GameObject(type: ObjectType.booster, x: 180.0, y: 180.0, angle: 90.0),
    GameObject(type: ObjectType.spring, x: 300.0, y: 380.0),
    GameObject(type: ObjectType.prism, x: 60.0, y: 540.0, angle: 45.0),
    GameObject(type: ObjectType.peg, x: 300.0, y: 500.0),
  ],
};
